version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: Build image and push
          command: |
            REGION="us-east-1"
            ECR_URL="020046395185.dkr.ecr.$REGION.amazonaws.com/circleci-demo"
            BUILD_NUMBER="${BUILD_NUMBER:-$(date +%s)}"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 020046395185.dkr.ecr.us-east-1.amazonaws.com
            docker build -t $ECR_URL:${BUILD_NUMBER} .
            docker push $ECR_URL:${BUILD_NUMBER}
  deploy:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: register task-def
          command: |
            aws ecs register-task-definition --cli-input-json file://task-definition.json

  service:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: create service
          command: |
            aws ecs create-service --cli-input-json file://service.json

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          context: Env
          filters:
            branches:
              only: dev
      - deploy:
          context: Env
          requires:
            - build
          filters:
            branches:
              only: dev
      - service:
          context: Env
          requires:
            - deploy
          filters:
            branches:
              only: dev