version: 2.1
jobs:
  test:
    docker:
      - image: python:3.7.1
    steps:
      - checkout
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run: 
          name: Build image and push
          command: |
            REGION="us-east-1"
            ECR_URL="020046395185.dkr.ecr.$REGION.amazonaws.com/circleci-demo"
            BUILD_NUMBER="${BUILD_NUMBER:-$(date +%s)}"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 020046395185.dkr.ecr.us-east-1.amazonaws.com
            docker build -t $ECR_URL:$BUILD_NUMBER \
              --build-arg VERSION="$BUILD_NUMBER" \
            docker push $ECR_URL:$BUILD_NUMBER
            docker tag $ECR_URL:$BUILD_NUMBER $ECR_URL:latest
            docker push $ECR_URL:latest
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master